version: '3.9'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=olivierChampionUsername
      - POSTGRES_PASSWORD=olivierChampionPassword
      - POSTGRES_DB=postgres
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - ./.docker/volumes/postgres-data:/var/lib/postgresql/data
  # redis:
  #   image: redis:6
  #   restart: always
  #   ports:
  #     - 127.0.0.1:6379:6379
    # volumes:
    #   - ./.docker/volumes/redis-data:/data

